### ISSUE TITLE
Add settings to keep all atributes on one line

### ISSUE THREAD

**Issue by maxyvon** [pmahend1/PrettyXML#104]
Please add the ability to keep all atributes on one line. This setting would be similar to **Position First Attribute On Same Line** but it would add the ability to keep them all on the same line.
On the exemple below, the **Checked** is what it could look like and the **Unchecked** is the _default_ configuration when _Position First Attribute On Same Line_ is checked.

**Checked :**
```
<Element Atribute="value" Atribute2="value2" />
```
**Unchecked :**
```
<Element Attribute="value"
         Atribute2="value2" />
```

When this setting would be checked, the behavior of  _Position First Attribute On Same Line_ could be impact.

**Comment by pmahend1** [comment]
Hi, thanks for the suggestion. Wouldn't it make the file horizontally so long?
