### ISSUE TITLE
Minimize not working

### ISSUE THREAD

**Issue by Longonot** [pmahend1/PrettyXML#125]
Trying to minimize not a large file...
The message comes up: Pretty XML Miminizing... and nothing happens from there...

**Comment by pmahend1** [comment]
Please share reproduction steps with sample XML.

**Comment by pmahend1** [comment]
I am sorry, but your attachments are not appearing on the issue. Could you please upload on GitHub page instead of replying through email?

**Comment by Longonot** [comment]
<img width="1431" alt="Shot1" src="https://github.com/pmahend1/PrettyXML/assets/15280947/157f7ac0-d680-4342-ba38-b7b7319cb250">
<img width="1435" alt="Shot2" src="https://github.com/pmahend1/PrettyXML/assets/15280947/94240552-e434-468a-82ed-02bbebcfc30d">
<img width="1432" alt="Shot3" src="https://github.com/pmahend1/PrettyXML/assets/15280947/2d48e01f-de28-4b19-9726-3a815f3bcabe">
<img width="1431" alt="Shot4" src="https://github.com/pmahend1/PrettyXML/assets/15280947/a73265ca-f593-400d-aa3a-51e2a30018fb">
[Excel Customizations XML.exportedUI.zip](https://github.com/pmahend1/PrettyXML/files/12545386/Excel.Customizations.XML.exportedUI.zip)

**Comment by pmahend1** [comment]
Your file type is selected as `PlainText` , please change it to `XML` 
Make sure XML is valid too.

**Comment by pmahend1** [comment]
Go to VS Code > Settings > Extensions > PrettyXML Settings and turn on Enable Logs.
Try to reproduce the issue. You will be able to see logs in Output window > Choose Pretty XML in drop-down. Please report logs here.
Once done you can turn off the setting.

![image](https://github.com/pmahend1/PrettyXML/assets/21352870/d30b1a15-a93c-4fe2-803e-ba67a5fe6bb9)

<img width="1039" alt="image" src="https://github.com/pmahend1/PrettyXML/assets/21352870/e90eb4b5-1476-478d-b73a-4888a8a8b465">

**Comment by Longonot** [comment]
[logs.txt](https://github.com/pmahend1/PrettyXML/files/12618050/logs.txt)
<img width="626" alt="Screenshot 2023-09-15 at 12 47 38" src="https://github.com/pmahend1/PrettyXML/assets/15280947/7553522f-3341-40c7-b15f-2896e1dabbf8">

A message popped up : Rendering paused for long line for perfomance reasons...this can be configured via Editor.stopRenderingLineAfter

So this could be a VS setting...

**Comment by pmahend1** [comment]
Please refer this : https://github.com/microsoft/vscode/issues/7772

This setting is not explicitly present. So you will have to open *Preferences > Open User Settings (JSON)* and add an entry for `editor.stopRenderingLineAfter` and set it to `20000` or something. Default is `10000`. Also try toggling word wrap in *View > Word Wrap*

Please note if minimize is working fine for smaller XML files then it is most probably rendering issue.
