### ISSUE TITLE
Settings Sharing

### ISSUE THREAD

**Issue by Schreck425** [pmahend1/PrettyXML#127]
This isn't really an issue so delete if needed.  This is more of a question.  Is there a way users can make sure they have the same extension settings as each other?  Me and another developer both use the extension but he must have used different settings so a minor change and a prettify causes the file to be very different.  I looked for where the settings get stored and could not find them.

**Comment by pmahend1** [comment]
Thanks for reporting.  This would be Visual Studio Code feature. Here is a possible solution.

https://stackoverflow.com/questions/35368889/how-can-i-export-settings

You would need to open **Preferences: Open User Settings (JSON)** ⇒ check anything with `prettyxml.settings.` these will be the ones which you have modified, it wont show the default settings. If you want to see default settings in JSON you can do so by opening **Preferences: Open Default Settings (JSON)**. Another thing to note is there are two different levels of settings for all extensions, make sure they are same viz. 
1. User settings
2. Workspace settings

Also you can take screenshots from Extension settings and compare too.
Let me know if I can be of more help.
