### ISSUE TITLE
Allow blank lines would be a nice feature

### ISSUE THREAD

**Issue by dbraynard** [pmahend1/PrettyXML#128]
I often leave blank lines when authoring an msbuild file. It would be nice if this extension could leave blank lines alone. Nice extension, otherwise.

**Comment by pmahend1** [comment]
Do you mean blank lines in comments or in general?

**Comment by dbraynard** [comment]
In general. Throughout the xlm.

**Comment by pmahend1** [comment]
I doubt that is possible with current implementation. That is because even space and tabs are considered white-spaces, so formatting might not be what we desire. 
I will see if I can find way. I will keep this open for further discussion.

**Comment by dbraynard** [comment]
Thanks. I think this only requires optionally leaving new line characters intact even for empty lines. I liked the formatting otherwise. It is hard to find a formatter that does exactly what I want.

**Comment by pmahend1** [comment]
I checked source code again and this is not possible at this time depending on how the XML is parsed for reformatting.
