### ISSUE TITLE
A feature proposal

### ISSUE THREAD

**Issue by MarkiianKhylynskyi** [pmahend1/PrettyXML#130]
It will be nice to be able to configure the maximum number of attributes allowed on a single line. If the number of attributes exceeds this value, the attributes will be broken up across multiple lines.
<img width="491" alt="Screenshot 2023-11-16 at 10 05 29" src="https://github.com/pmahend1/PrettyXML/assets/88542944/932bbf8e-ea4c-4287-a57d-e001156e8a17">

**Comment by pmahend1** [comment]
Hello, 

Thanks for reporting a feature request. I am quite confused about the screenshot since the examples for Maximum number 1 or 2 are not consistent so I am wondering what is expected here.

**Comment by MarkiianKhylynskyi** [comment]
<img width="845" alt="Screenshot 2023-11-18 at 10 46 47" src="https://github.com/pmahend1/PrettyXML/assets/88542944/cf73e192-d140-4ab8-8d6b-bdf1d3767092">

**Comment by pmahend1** [comment]
<img width="1578" alt="Screenshot 2023-11-18 at 11 21 30 AM" src="https://github.com/pmahend1/PrettyXML/assets/21352870/0cdbd06e-c0b5-40ea-bef1-5b1e403a7053">

In the red outlined XML there are 0 attributes on the first line of start pf element.  Is that what is expected when `Maximum Number = 3`? I am not understanding how it is supposed to format when that supposed setting is set the formatting.

Could you please elaborate?

**Comment by MarkiianKhylynskyi** [comment]
Suppose that MaximumNumber = 2. If an element has two or fewer attributes, then it is on a single line. If an element has more than two attributes, then all its attributes are on distinct lines.

**Comment by pmahend1** [comment]
Based on the outlined example it is harder to implement it with the current logic. However if it were maximum 2 at every line then it is possible i.e 

```xml
<Label BackgroundColor="Aquamarine" FontSize="25
       HorizontalOptions="Center" VerticalOptions="Center" />
```

**Comment by pmahend1** [comment]
@MarkiianKhylynskyi  Let me know if the above sounds good. If yes, I will proceed to implement it.

**Comment by MarkiianKhylynskyi** [comment]
No. I meant this https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#attribute-tolerance

**Comment by pmahend1** [comment]
I am still confused about the examples mentioned there. For example with tolerance level =2, the one with  "Sample Text 3" seems to be an outlier. There are 0 attributes on first line.

![687474703a2f2f692e696d6775722e636f6d2f7a5259455645562e706e67](https://github.com/pmahend1/PrettyXML/assets/21352870/5a2c4055-981a-4834-9d2e-ff4269d2c336)

case 1: if first attribute on same line = false then what I think it should be 
```xml
<TextBlock 
    Margin="4,6,4,8" FontSize="12"
    Text="Sample Text 3" /> 
```

case 2 : if first attribute on same line = true, then
```xml
<TextBlock Margin="4,6,4,8" FontSize="12"
           Text="Sample Text 3" /> 
```

If either of these are intended then I can go ahead and implement this.

**Comment by MarkiianKhylynskyi** [comment]
@pmahend1 No. The idea behind this is that when there are few attributes, they are all placed on one line. And if there are many attributes, then they are all placed in a column for one attribute per a line.

**Comment by MarkiianKhylynskyi** [comment]
@pmahend1 I think you can generalize the setting "Position All Attributes On First Line" and make it numerical. You can add intermediate values so that `Checked = ∞` and `Unchecked = 0`.

**Comment by pmahend1** [comment]
I get the idea but why does only the aforementioned example is different from the first two?
