### ISSUE TITLE
indentSpaceLength doesn't seem to work

### ISSUE THREAD

**Issue by sssutd** [pmahend1/PrettyXML#143]
This setting doesn't seem to work in the latest update. It used to work OK in the past.
`"prettyxml.settings.indentSpaceLength": 2
`

A quick test:
```
<a>
<b />
</a>
```
Format result:
```
<a>
    <b />
</a>
```
Got 4 spaces before \<b> instead of the expected 2.

**Comment by pmahend1** [comment]
Thanks for reporting. I will check and fix.

**Comment by pmahend1** [comment]
I did a quick check. I am unable to reproduce this on my end. 
Please ensure the setting is set to 2.

![image](https://github.com/pmahend1/PrettyXML/assets/21352870/61d4bd88-977d-40dc-9634-2c1300240d2c)

Please provide log file to investigate further.

## Enabling PrettyXML logs
- Go to VS Code Preferences
- Go to user tab
- Scroll down and select **PrettyXML Settings**
- Turn on setting enable logs
![image](https://github.com/pmahend1/PrettyXML/assets/21352870/f2b38a44-36a0-47ae-9ce8-f54a6c0ffb74)
- Run Format document/Pretty XML editor commands(i.e format with PrettyXML)
- Go to output tab down editor panel
- In dropdown select PrettyXML
![image](https://github.com/pmahend1/PrettyXML/assets/21352870/386edfe4-3688-46b9-bd22-da0327755557)
- Once done you can switch logs settings to Off.
-

**Comment by sssutd** [comment]
Thanks for checking this. 

The indent setting is indeed 2.
![image](https://github.com/pmahend1/PrettyXML/assets/158745063/82dfde1f-1b6a-4c97-a262-fca864d90a76)

The log also shows it's 2:
```
[ INFO - 12:24:03 AM] provideDocumentFormattingEdits start
[ INFO - 12:24:03 AM] getDocumentRange start
[ INFO - 12:24:03 AM] getDocumentRange end
[ INFO - 12:24:03 AM] formatXml start
[ INFO - 12:24:03 AM] formatWithCommandLine start
[ INFO - 12:24:03 AM] converted input to json {"xmlString":"<a>\r\n<b />\r\n</a>","actionKind":"Format","formattingOptions":{"indentLength":2,"useSingleQuotes":false,"useSelfClosingTags":true,"formatOnSave":false,"allowSingleQuoteInAttributeValue":true,"addSpaceBeforeSelfClosingTag":true,"wrapCommentTextWithSpaces":false,"allowWhiteSpaceUnicodesInAttributeValues":true,"positionFirstAttributeOnSameLine":true,"positionAllAttributesOnFirstLine":false,"preserveWhiteSpacesInComment":true,"enableLogs":true}}
[ INFO - 12:24:03 AM] Starting dotnet childProcess at c:\Users\sss\.vscode\extensions\prateekmahendrakar.prettyxml-4.1.3\lib\XmlFormatter.CommandLine.dll 
[ INFO - 12:24:04 AM] childProcess stdOutData:  <a>
    <b />
</a>
[ INFO - 12:24:04 AM] Formatted text: <a>
    <b />
</a>
[ INFO - 12:24:04 AM] formatXml end
[ INFO - 12:24:04 AM] provideDocumentFormattingEdits start
```
Yet the Format result has 4 spaces, both in the log and the editor.
![image](https://github.com/pmahend1/PrettyXML/assets/158745063/9b133d71-ac2d-4d61-8c9e-7fabf6c53c78)
