### ISSUE TITLE
Extension causes Avalonia Preview Button to Disappear

### ISSUE THREAD

**Issue by kaanyalova** [pmahend1/PrettyXML#146]
Before installing this extension:
![resim](https://github.com/pmahend1/PrettyXML/assets/76952012/f7f4ec46-deee-4530-8e18-22b113852073)

After installing this extension:
![resim](https://github.com/pmahend1/PrettyXML/assets/76952012/311102e7-a0de-4feb-b271-6b26ea803567)

To reproduce:
1. Install the [Avalonia for VSCode](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.vscode-avalonia) extension
2. See the preview button on axaml files
3. Install this extension
4. The preview button is gone

**Comment by pmahend1** [comment]
The other day I [got request to add `.axaml` to identifiable language extensions](https://github.com/pmahend1/PrettyXML/issues/135). The issue you are seeing should be fixed if Avalonia team changes their command when clauses from `editorLangId == AXAML` to `resourceExtname == .axaml`
