### ISSUE TITLE
Not format the code when .NET 6 not install

### ISSUE THREAD

**Issue by sokheang-dev** [pmahend1/PrettyXML#154]
OS: macOS Sonoma 14.4.1
Dotnet: 8.0.204
VS Code: 1.81.1

When I format the XML using the extension the error below is shown:

You must install or update .NET to run this application. App: /Users/sokheang/.vscode/extensions/prateekmahendrakar.prettyxml-4.5.1/lib/XmlFormatter.CommandLine.dll Architecture: x64 Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64) .NET location: /usr/local/share/dotnet/ The following frameworks were found: 8.0.4 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App] Learn more: https://aka.ms/dotnet/app-launch-failed To install missing framework, download: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=osx-x64&os=osx.14

Does the extension require .NET 6 installed? I have .NET 8 installed.

**Comment by pmahend1** [comment]
Due to some issue recent dotnet, it is not identifying version 6. For time being please install dotnet 6 as well. 
I would like to make it 8 minimum version but that would mean it would work only on dotnet 8 and higher. 
I will check further and will make that change if thats necessary.
