### ISSUE TITLE
Problems in VS Code Insiders edition

### ISSUE THREAD

**Issue by jmfontana** [pmahend1/PrettyXML#160]
For some reason the 'Minimize' option works in my installation of VS Code (insiders edition) but the normal 'prettify' functionality where the document is reflowed does not. I work on a Mac. If I do CMD-KL, the XML code is minimized. When I right click and I choose Prettify XML, I get the little pop up window "Pretty XML: formatting" but nothing happens. 

I thought this was because the XML document was too long but I've tried with minimal ones and I have the same problem.

**Comment by pmahend1** [comment]
Hello,

- What version of dotnet do you have?
- Do you see any error? Can you share log by turning it on in PrettyXML settings

**Comment by pmahend1** [comment]
No update. So closing this. Please open a new issue if it persists.
