### ISSUE TITLE
XmlFormatter.CommandLine.dll not signed

### ISSUE THREAD

**Issue by AZphanus** [pmahend1/PrettyXML#161]
Just a suggestion. The Dll can be blocked by those that block unsigned Dlls. Whitelisting on file hash will work but if you update the dll a new hash would have to be generated.

**Comment by pmahend1** [comment]
Thanks for the info. I myself have not come across an issue where this is the case. I assume one would want to whitelist VSCode folder to be ignored by AntiVirus if that's what is blocking it. What would be a solution for this?

**Comment by AZphanus** [comment]
XmlFormatter.dll is also affected by this as well.  Yeah either the person would have to trust the directory that the dlls reside in. Though it looks like the folder name contains the version of the software so that would change per version. Or you can sign the dlls when you compile them. Though you may have to pay for that or see if you can self-sign the dlls. Though I'm not an expert on signing code for external user support.

**Comment by pmahend1** [comment]
Thank you 😄  I will check it out.  

> Though it looks like the folder name contains the version of the software so that would change per version.

By the way one can use wild-carded paths to be whilte-listed or the whole VS Code extensions folder.

**Comment by pmahend1** [comment]
It is not high priority. There are a lot of applications which require you to whitelist on anti-virus. 
Its open source and free software. Assuming we have to pay for getting certificate signing it can be done if there is some sponsorship I will keep it in mind and implement it if feasible with low cost in coming months.

**Comment by pmahend1** [comment]
Closing as not planned now.
