### ISSUE TITLE
Take as an error labels with Spanish characters (ñ, á, ü, etc.).

### ISSUE THREAD

**Issue by zherar7ordoya** [pmahend1/PrettyXML#163]
It's a shame because it's the formatter I like the most, but I can't use it on local projects for this reason.

**Comment by pmahend1** [comment]
@zherar7ordoya Thanks for reporting. Please share a sample xml with the issue you are seeing.

**Comment by zherar7ordoya** [comment]
XML:
<?xml version="1.0" encoding="utf-8"?>
<Configuracion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Id="0" Bloqueado="false" Borrado="false">
  <ContraseñaMaximoFallos>5</ContraseñaMaximoFallos>

ERROR:
Unhandled exception. System.Exception: The '�' character, hexadecimal value 0x251C, cannot be included in a name. Line 3, position 12. at XmlFormatter.CommandLine.ConsoleProgram.Main(String[] args) at XmlFormatter.CommandLine.ConsoleProgram.<Main>(String[] args)

**Comment by pmahend1** [comment]
XML parsed and reformatted with dotnet XML parser.
Currently only English characters are supported. I believe there is a reason for that. 
I will see if we can circumvent that.
