### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by ceh-ylhy** [pmahend1/PrettyXML#165]
![record2](https://github.com/user-attachments/assets/2808910f-7571-4b2d-9405-8cb21d6efcba)

**Comment by ceh-ylhy** [comment]
Here's a sample
[Uploading entitygroups.xml.txt…]()

**Comment by ceh-ylhy** [comment]
> Sorry. What improvement are you suggesting?

Large file scenarios, Formatting with extra spaces

**Comment by pmahend1** [comment]
Okay. will look into it.

**Comment by pmahend1** [comment]
I found a work-around but that messes up formatting of other files.
