### ISSUE TITLE
Formatting doesn't seem to work when using with .xaml files.

### ISSUE THREAD

**Issue by asusralis** [pmahend1/PrettyXML#167]
I am trying to format (on save) for .xaml files, but it only works with .xml files. I set the association for .xaml to .xml, but it still doesn't work. Only when I switch the file to .xml.

It needs to be set to .xaml because I am also using Noesis which only works with .xaml files.

**Comment by pmahend1** [comment]
XAML is built on top of XML.May be you have another extension installed that considers Xaml as a separate language. When you open XAML if you see the language set to XAML, you need to change it to XML.
