### ISSUE TITLE
"&amp" in attributes are reformatted as "&"

### ISSUE THREAD

**Issue by JoePlant** [pmahend1/PrettyXML#61]
I had the following xml document.
```xml
<node a="here &amp; now">
  <node>more...</node>
  <node>black &amp; white</node>
</node>
```

After running Prettify 0.7.1 (latest version) it produces invalid xml

```xml
<node a="here & now">
  <node>more...</node>
  <node>black &amp; white</node>
</node>
```

Note that the &amp; in the attribute is incorrectly changed to "&" but the &amp in the text isn't.

**Comment by pmahend1** [comment]
@JoePlant Thanks for reporting. I will fix it in next release which should be pretty soon.
