### ISSUE TITLE
Add Linux support?

### ISSUE THREAD

**Issue by TryTryAgain** [pmahend1/PrettyXML#64]
I see you have a MacOS version, any chance you may be adding Linux support as well?

**Comment by pmahend1** [comment]
Is it not working on Linux ? It should work if you have mono and/or dotnet installed.

**Comment by Moilleadoir** [comment]
Doesn’t seem to do much for me. I get this warning when enabling it.

> The edge native module is not available at /home/sean/.vscode/extensions/prateekmahendrakar.prettyxml-0.8.1/node_modules/electron-edge-js/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge

**Comment by pmahend1** [comment]
Aah. I kind of understand the issue,  I will have to compile it against Linux as well. I will try to do this ASAP.

**Comment by pmahend1** [comment]
@Moilleadoir I tried fixing this on Ubuntu 20, their is weird error I am not able to fix right now.

**OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by )**
[](https://askubuntu.com/questions/1143268/how-to-install-a-libc6-version-2-29)

**2.29** is not present anymore , I will try bring this up on electron-edge-js and see if we get a solution.

**Comment by pmahend1** [comment]
I have added a backup option for linux , please check and let me know if it doesnt work.
Please note you need to install dotnet and have it in the path to make it work.

**Comment by pmahend1** [comment]
I am gonna create a linux VM and check. What OS are you on? @Moilleadoir

**Comment by Moilleadoir** [comment]
I’m using Manjaro with Cinnamon desktop.  The package I installed is `visual-studio-code-bin` from the Arch User Repository, which is the official MS binary.  The main (Community Repo) version is built from source and may not have all the same features as the MS distribution.

Honestly though, if you’re doing this for me, I’d say don’t bother as my use of it will be pretty minimal.  If you’re just doing it to improve your extension then I’m happy to help out.

**Comment by pmahend1** [comment]
@Moilleadoir I installed Ubuntu 20 LTS , it worked fine for me after following the steps

- [Install dotnet](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-)
- Verify that you can run dotnet command on terminal
- Install C# extension [https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp]
