### ISSUE TITLE
This extension stop native ctrl+p in vscode

### ISSUE THREAD

**Issue by alfnielsen** [pmahend1/PrettyXML#7]
`ctrl+p` is an essential short-cut in vscode (at least on pc)
And while this extension is enabled it stops the native `ctrl+p`

I can see that the package.json file add `ctrl+p f` 
I guess this is the reason for the problem! (I don't know how to make multi tab commands)

When I disable this extension, the `ctrl+p` work normal again.

**Comment by pmahend1** [comment]
@alfnielsen thanks for reporting.
I had not noticed it. I will probably change the keybinding something.

Till then as a workaround can you use workspace keybindings and try https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by pmahend1** [comment]
Fixed by #9 with extension Version 0.0.10
