### ISSUE TITLE
Add settings for indent with tabs

### ISSUE THREAD

**Issue by informagico** [pmahend1/PrettyXML#70]
Please add the ability to indent XML with tabs and not spaces, I was not able to find the source code for the .dll otherwise I could have made a PR on that 😀

**Comment by pmahend1** [comment]
Thanks for raising this.

It was intentional because of the space count doesn't always match the tab x N count.Also tab can mean 2 spaces or 4 spaces
I will add you to that project, would you be able to fork it ?
@informagico

**Comment by informagico** [comment]
@pmahend1 Sure! Count me in, I'll take a look on that.

**Comment by informagico** [comment]
@pmahend1  why don't you use the native System.Xml (with XmlWriterSettings to handle various options)?
Doing this will also fix the other issue with different characters encoding (emoji?).

**Comment by pmahend1** [comment]
C# XML Writer doesn't explitly provide option for keeping the first attribute in the same line as StartElement.

I was not able to override to change its behavior to make it dynamic. 
I scoured through various XML writer classes from.Net std,. Net Core and Framework source (some of them are obsolete now), couldn't get what I needed. 

I haven't found agnostic xml writer in open source that does this so far. 

If you have a solution in mind feel free to PR it.

**Comment by pmahend1** [comment]
Indenting with tabs is not supported because it will ruin the spacing and alignment of attributes .
However the indent length setting can be changed between 2, 4 , 8 spaces right now, which should suffice.

Closing this now.
