### ISSUE TITLE
Cannot format *.config files

### ISSUE THREAD

**Issue by celluj34** [pmahend1/PrettyXML#75]
Hello;

I am trying to use the global formatting command on VSCode Windows v1.59.0 (`ALT + SHIFT + F`) but I get the following error in the status bar:

![image](https://user-images.githubusercontent.com/10264021/129075750-8d5b33fb-f5e4-43fc-bea9-69e4dd625931.png)

Formatting does work with the context menu, the custom formatting command (`CTRL + K, L`), and on save, but I don't want to have to memorize another key bind for the same functionality.

**Comment by pmahend1** [comment]
Pretty XML is not registered as formatting provider(format as you type) . So you cannot use default key binding ALT+SHIFT+F for that as of now.
As of now its how it is , there are some limitations on making it formatting provider.

I will make a note of this however, if I can implement formatting provider on the fly then I will update.

**Comment by pmahend1** [comment]
This ability has been added in version 1.x.x
Please check
