### ISSUE TITLE
Minimize did not work

### ISSUE THREAD

**Issue by liliancunha** [pmahend1/PrettyXML#76]
Hi,

I have installed the Pretty XML on Mac using Visual Code by Marketplace, and took the message error: "Command 'Pretty XML: Minimize' resulted in an error (command 'prettyxml.minimizexml' not found)", how should I proceed?

**Comment by pmahend1** [comment]
Do you have DotNet SDKs installed on your machine?
Does prettify XML work?

**Comment by liliancunha** [comment]
Hi,

I have installed after your message and still not working. I uninstall the extension and reinstalled and still not working. I am using MacOS

**Comment by pmahend1** [comment]
Thats weird , can you run `dotnet` command on terminal? 
Also check if you have mono installed

**Comment by pmahend1** [comment]
Please check with version 1.0.0.

If the issue still persist please provide verbose log when you open vscode and try to access Minimize command.

Also let me know if you can find mono along with dotnet in command environment (you should be able to run `dotnet` command without error)

**Comment by pmahend1** [comment]
There is no update from the user and this doesn't seem to be an issue any more. So closing this.
