### ISSUE TITLE
Can we have access to the source code for the XmlFormatter.VSCode

### ISSUE THREAD

**Issue by aboimpinto** [pmahend1/PrettyXML#91]
Hello, 

I'm trying to learn how to create a VSCode that formats the code on the fly, auto-close tags etc..etc. and I would like to see what is the Dlls that you have in the libs folder.

Do you have that code? Where did you get it?

best regards
Paulo Aboim Pinto

**Comment by pmahend1** [comment]
I have that in a private library that is not MIT open-source licensed intentionally. Unfortunately on-the-fly formatting is not possible currently.

**Comment by aboimpinto** [comment]
thanks for the answer ...
can you point me to a place where can I learn how this lib can be done? 

thanks a lot
Paulo Aboim Pinto

**Comment by pmahend1** [comment]
I can add you to the repo as a contributor if you could ensure you would contribute to same repo.
What is your Github ID that needs the access?

**Comment by aboimpinto** [comment]
that is a great idea ... thank for the trust. 
my github id: 1231687

**Comment by pmahend1** [comment]
I think I need the github username. Is it same `aboimpinto` ?

**Comment by aboimpinto** [comment]
> I think I need the github username. Is it same `aboimpinto` ?

yes ... it's AboimPinto

**Comment by pmahend1** [comment]
Done.

**Comment by aboimpinto** [comment]
how do I find the private repository?
